# Generated by Django 3.2.23 on 2024-05-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('contact', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
