# Generated by Django 3.2.23 on 2024-05-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROJECTApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milage_date', models.DateField()),
                ('bill_no', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kilometer_reading', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tyre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixing_date', models.DateField()),
                ('fixing_kilometer_reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resolve_vehicle_number', models.CharField(max_length=100)),
            ],
        ),
    ]
