# Generated by Django 3.2.23 on 2024-05-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROJECTApp', '0002_milage_tyre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milage',
            name='amount',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='milage',
            name='bill_no',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='milage',
            name='kilometer_reading',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='milage',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
