# Generated by Django 3.2.23 on 2024-05-29 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PROJECTApp', '0003_auto_20240528_1111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Milage',
        ),
        migrations.DeleteModel(
            name='Tyre',
        ),
    ]
