# Generated by Django 3.2.23 on 2024-05-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROJECTApp', '0004_auto_20240529_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tyre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('tyre1', models.CharField(max_length=100)),
                ('tyre2', models.CharField(max_length=100)),
                ('tyre3', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('kilometer', models.FloatField()),
                ('bill_number', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
            ],
        ),
    ]
