# Generated by Django 3.2.23 on 2024-05-29 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PROJECTApp', '0005_tyre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tyre',
            old_name='tyre1',
            new_name='tyre_issue',
        ),
        migrations.RemoveField(
            model_name='tyre',
            name='tyre2',
        ),
        migrations.RemoveField(
            model_name='tyre',
            name='tyre3',
        ),
    ]
