# Generated by Django 3.2.23 on 2024-05-29 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PROJECTApp', '0006_auto_20240529_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tyre',
            old_name='tyre_issue',
            new_name='tyre_type',
        ),
    ]
