# Generated by Django 3.2.23 on 2024-05-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROJECTApp', '0007_rename_tyre_issue_tyre_tyre_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverName', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('billNumber', models.CharField(max_length=100)),
                ('fuelStation', models.CharField(max_length=100)),
                ('liter', models.FloatField()),
                ('amount', models.FloatField()),
                ('readings', models.FloatField()),
            ],
        ),
    ]
