# Generated by Django 3.2.23 on 2024-05-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROJECTApp', '0008_fuel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mileage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastFilledKilometer', models.CharField(max_length=100)),
                ('presentKilometer', models.CharField(max_length=100)),
                ('numberOfLiter', models.CharField(max_length=100)),
            ],
        ),
    ]
