# Generated by Django 3.2.23 on 2024-05-30 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PROJECTApp', '0009_mileage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mileage',
            old_name='lastFilledKilometer',
            new_name='last_filled_kilometer',
        ),
        migrations.RenameField(
            model_name='mileage',
            old_name='numberOfLiter',
            new_name='number_of_liter',
        ),
        migrations.RenameField(
            model_name='mileage',
            old_name='presentKilometer',
            new_name='present_kilometer',
        ),
    ]
