# Generated by Django 3.2.23 on 2024-05-30 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PROJECTApp', '0012_mileage_calculatedmileage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mileage',
            name='calculatedMileage',
        ),
    ]
