# Generated by Django 3.2.23 on 2024-06-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROJECTApp', '0014_rename_lastname_user_license'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=25)),
                ('vnumber', models.CharField(max_length=10)),
                ('cnumber', models.CharField(max_length=17)),
                ('rcnumber', models.CharField(max_length=10)),
            ],
        ),
    ]
