# Generated by Django 3.2.23 on 2024-06-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROJECTApp', '0016_auto_20240603_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
    ]
