# Generated by Django 3.2.23 on 2024-06-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROJECTApp', '0019_remove_user_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel',
            name='vnumber',
            field=models.CharField(default='DEFAULT_VALUE', max_length=100),
        ),
    ]
