# Generated by Django 3.2.23 on 2024-06-14 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PROJECTApp', '0021_remove_fuel_vnumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fuel',
        ),
    ]
