# Generated by Django 3.2.23 on 2024-06-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROJECTApp', '0022_delete_fuel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vnumber', models.CharField(max_length=10)),
                ('driverName', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('billNumber', models.CharField(max_length=100)),
                ('fuelStation', models.CharField(max_length=100)),
                ('liter', models.FloatField()),
                ('amount', models.FloatField()),
                ('readings', models.FloatField()),
            ],
        ),
    ]
