# Generated by Django 3.2.23 on 2024-06-14 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PROJECTApp', '0023_fuel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tyre',
        ),
    ]
