# Generated by Django 3.2.23 on 2024-06-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROJECTApp', '0024_delete_tyre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tyre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vnumber', models.CharField(max_length=10)),
                ('driver_name', models.CharField(max_length=100)),
                ('tyre_type', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('kilometer', models.FloatField()),
                ('bill_number', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
            ],
        ),
    ]
