# Generated by Django 3.2.23 on 2024-06-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROJECTApp', '0026_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='old_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
