# Generated by Django 3.2.23 on 2024-06-19 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PROJECTApp', '0027_user_old_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='old_password',
            new_name='new_password',
        ),
    ]
