# Generated by Django 3.2.23 on 2024-06-25 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PROJECTApp', '0031_delete_passwordchangerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PROJECTApp.user')),
            ],
        ),
    ]
