# Generated by Django 3.2.23 on 2024-06-25 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PROJECTApp', '0032_passwordrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordRequest',
        ),
    ]
