# Generated by Django 3.2.23 on 2024-06-27 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PROJECTApp', '0038_passwordrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordRequest',
        ),
    ]
