# Generated by Django 3.2.23 on 2024-07-03 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PROJECTApp', '0039_delete_passwordrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tyre',
        ),
    ]
