# Generated by Django 3.2.23 on 2024-07-03 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PROJECTApp', '0041_tyre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fuel',
        ),
    ]
