# Generated by Django 3.2.23 on 2024-07-08 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PROJECTApp', '0043_fuel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='rcnumber',
        ),
    ]
