# Generated by Django 3.2.23 on 2024-07-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROJECTApp', '0044_remove_vehicle_rcnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.IntegerField(default=0),
        ),
    ]
